# Generated by Django 4.1.2 on 2023-04-01 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sos',
            old_name='gender',
            new_name='relation',
        ),
    ]
